version: '3.9'

services:
  nginx: #web server container
    #https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/
    image: nginx:stable-bullseye
    restart: unless-stopped
    volumes:
      # - nginx-data:/usr/share/nginx/html
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
          
  postgres:
      #https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
      image: postgres:12.16-bullseye
      restart: unless-stopped
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: example
  
  php-fpm:
      image: php:fpm-bullseye
      restart: unless-stopped
      volumes:
        # - phpdata:/var/www/html
        - ./src:/var/www/html
      
volumes:
#   nginx-data:
  pgdata:
#   phpdata: