version: '3.9'

services:
  nginx:
    image: nginx:stable-bullseye
    container_name: keymgr_nginx
    restart: unless-stopped
    volumes:
      - ./BasicDemo:/var/www/html:rw
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/logs/nginx
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8080:80"

  postgres:
    image: postgres:12.16-bullseye
    container_name: keymgr_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: example
      #ideally we specify POSTGRES_USER and POSTGRES_DB so that we're not using the superadmin.
      #eventually user:keymgr, database:keymgr. 
      #Otherwise, this defaults to 'postgres' for both

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keymgr_php
    restart: unless-stopped
    volumes:
      - ./BasicDemo:/var/www/html:rw


