###############################################################################
# Filename:   docker-compose.yaml
# Authors:    Zachary Abela-Gale, Liam Henry
# Date:       2023/11/25
# Purpose:    Configures VSCode devcontainer, and supporting services.
###############################################################################
version: '3.9'

services:
  # Container used by VSCode
  developerapp:
    build:
      context: .
      dockerfile: Dockerfile.developmentapp
    container_name: keymgr_developer
    restart: unless-stopped
    command: sleep infinity
    depends_on:
      - php-fpm
      - postgres
      - nginx
    volumes:
      - ../../:/workspaces:cached
      - ~/.ssh:/root/.ssh #Cheap way to provide SSH access per user

  nginx:
    image: nginx:stable-bullseye
    container_name: keymgr_nginx
    restart: unless-stopped
    volumes:
      - ${WEB_DATA}:/var/www/html:rw
      - ../docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ${LOGDIR}/nginx:/var/logs2/nginx
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8080:80"

  postgres:
    image: postgres:12.16-bullseye
    container_name: keymgr_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      # Use the postgres-data volume if you want to persist data locally. 
      # (Also uncomment volumes below.)
      #- postgres-data:/var/lib/postgresql/data
      - ${LOGDIR}/postgres:/var/log/postgresql
      - ${INIT_SCRIPTS}:/docker-entrypoint-initdb.d/
    
    # Use the tmpfs mount if you want to reset the database 
    tmpfs: /var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: keymgr_php
    restart: unless-stopped
    volumes:
      - ${WEB_DATA}:/var/www/html:rw
    #This feels hacky, but I can't find a better solution.
    command: >
      | sh && chown -R www-data.www-data /var/www
    

#volumes:
  #postgres-data:
