###############################################################################
# Filename:   docker-compose.yaml
# Authors:    Zachary Abela-Gale, Liam Henry
# Date:       2023/11/25
# Purpose:    Configures VSCode devcontainer, and supporting services.
###############################################################################
version: '3.9'

services:
  
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.developmentapp
    container_name: keymgr_developer
    restart: unless-stopped
    command: sleep infinity
    depends_on:
      - php-fpm
      - postgres
      - nginx
    volumes:
      - ../../:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh:rw #Cheap way to use host SSH keys per user
    networks:
      - KeyMgr

  nginx:
    image: nginx:stable-bullseye
    container_name: keymgr_nginx
    restart: unless-stopped
    volumes:
      # - ${WEB_DATA}:/var/www/html:rw
      - ../KeyMgr:/var/www/html:rw
      - ../docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8080:80"
    networks:
      - KeyMgr

  postgres:
    image: postgres:12.16-bullseye
    container_name: keymgr_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      # Use the postgres-data volume if you want to persist data locally. 
      # (Also uncomment volumes below.)
      #- postgres-data:/var/lib/postgresql/data
      # - ${INIT_SCRIPTS}:/docker-entrypoint-initdb.d/
      - ../PostgresScripts:/docker-entrypoint-initdb.d/
    
    # Use the tmpfs mount if you want to reset the database 
    tmpfs: /var/lib/postgresql/data

    environment:
      # POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_PASSWORD: "keymgr"
    networks:
      - KeyMgr

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: keymgr_php
    restart: unless-stopped
    volumes:
      - ${WEB_DATA}:/var/www/html:rw
    #This feels hacky, but I can't find a better solution.
    command: >
      | sh && chown -R www-data.www-data /var/www
    networks:
      - KeyMgr
    

#volumes:
  #postgres-data:

networks:
  KeyMgr: