###############################################################################
# Filename:   docker-compose.yaml
# Authors:    Zachary Abela-Gale, Liam Henry
# Date:       2023/11/25
# Purpose:    Configures VSCode devcontainer, and supporting services.
###############################################################################
version: '3.9'

services:
  
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.developmentapp
    container_name: keymgr_developer
    restart: unless-stopped
    command: sleep infinity
    depends_on:
      - php-fpm
      - postgres
      - nginx
    volumes:
      - ../../:/workspaces:cached
      # Might be a better way to transfer host SSH keys, but it works.
      - ~/.ssh:/home/vscode/.ssh
    networks:
      - KeyMgr

  nginx:
    image: nginx:stable-bullseye
    container_name: keymgr_nginx
    restart: unless-stopped
    volumes:
      - ../KeyMgr:/var/www/html
      - ../docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8080:80"
    networks:
      - KeyMgr

  postgres:
    image: postgres:12.16-bullseye
    container_name: keymgr_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      # Use the postgres-data volume if you want to persist data locally. 
      # (Also uncomment volumes below.)
      #- postgres-data:/var/lib/postgresql/data
      - ../docker/postgresql/initdb:/docker-entrypoint-initdb.d/
    
    # Use the tmpfs mount if you want to reset the database 
    tmpfs: /var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "keymgr"
      POSTGRES_DB: KeyMgr
    networks:
      - KeyMgr

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: keymgr_php
    restart: unless-stopped
    volumes:
      - ../KeyMgr:/var/www/html
    command: >
      | sh && chown -R www-data.www-data /var/www
    networks:
      - KeyMgr
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ../docker/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@keymgr.com
      PGADMIN_DEFAULT_PASSWORD: keymgr
      PGADMIN_DISABLE_POSTFIX: "disabled"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    networks:
      - KeyMgr
    ports:
      - "8081:80"
  
volumes:
  pgadmin-data:
  #postgres-data:

networks:
  KeyMgr: