###############################################################################
# Filename:   docker-compose.yaml
# Authors:    Zachary Abela-Gale, Liam Henry
# Date:       2023/11/25
# Purpose:    Configures VSCode devcontainer, and supporting services.
###############################################################################
version: '3.9'

services:
  
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.developmentapp
    container_name: keymgr_developer
    restart: unless-stopped
    command: sleep infinity
    depends_on:
      - php-fpm
      - postgres
      - nginx
    volumes:
      - ../../:/workspaces:cached
      # SSH-Agent would be a better way to transfer host SSH keys, 
      # but this doesn't require admin rights if not an agent is not already installed.
      - ~/.ssh:/home/vscode/.ssh
      - node:/workspaces/KeyMgr/KeyMgr/node_modules
      - vendor:/workspaces/KeyMgr/KeyMgr/vendor
    # Reset the log file on container restarts.
    tmpfs:
      - /workspaces/KeyMgr/KeyMgr/storage/logs/
    networks:
      - KeyMgr

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: keymgr_nginx
    restart: unless-stopped
    volumes:
      - ../KeyMgr:/var/www/html
      - node:/var/www/html/node_modules
      - vendor:/var/www/html/vendor
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8080:80"
    networks:
      - KeyMgr

  postgres:
    image: postgres:16-alpine
    container_name: keymgr_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

    environment:
      POSTGRES_PASSWORD: "keymgr"
      POSTGRES_DB: KeyMgr
    networks:
      - KeyMgr

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: keymgr_php
    restart: unless-stopped
    volumes:
      - ../KeyMgr:/var/www/html
      - node:/var/www/html/node_modules
      - vendor:/var/www/html/vendor
    command: >
      | sh && chown -R www-data.www-data /var/www/html
    networks:
      - KeyMgr
    environment:
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: client_host=keymgr_developer client_port=9003

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@keymgr.com
      PGADMIN_DEFAULT_PASSWORD: keymgr
      PGADMIN_DISABLE_POSTFIX: "disabled"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    networks:
      - KeyMgr
    ports:
      - "8081:80"
  
volumes:
  pgadmin-data:
  postgres-data:
  node:
  vendor:

networks:
  KeyMgr:
